### ISSUE TITLE
Sentence Error: Chapter 3 - between prompt 15 and 16

### ISSUE THREAD

**Issue by realuser** [jvns/pandas-cookbook#24]
After In[15] there is a sentence that reads:

"This is a big array of Trues and Falses, one for each row in our dataframe. When we index our dataframe with this array, we get just the rows where."

If you read the 2nd sentence above you'll see that it seems be missing the end of the sentence.

**Comment by mkuzak** [comment]
Looks like this has been already fixed.
This issue can be closed.
