### ISSUE TITLE
Cookbook 5 url

### ISSUE THREAD

**Issue by aabroder** [jvns/pandas-cookbook#34]
First, thank you for these tutorials - they've been very helpful!
I've had a problem with the scraping tutorial in that, while the file does download, it has problems with this line:
weather_mar2012 = pd.read_csv(url, skiprows=16, index_col='Date/Time', parse_dates=True, encoding='latin1')
If I skip 16 rows, I get "ValueError: No columns to parse from file"
If I skip 15, I see the data, but it leaves a blank line on top and seem to do any of the rest - index_col, parse_dates or encoding.
This could be a problem on my end - I'm using anaconda with python 3.4. But I wasn't able to find anything with initial searches so I thought I'd ask here.
Thanks for any guidance you can give.

**Comment by daviddou82** [comment]
can we see your full code and the file you are try to read?

**Comment by aabroder** [comment]
Once I saw the error, I went back and did straight copy/paste from the tutorial to make sure I wasn't making any typing errors. Here's what I have:

In [1]: import pandas as pd
    pd.set_option('display.mpl_style', 'default')
    print('Ready')

I don't use "figsize(15,3)" since that doesn't seem to work with python 3. BTW, here's everything I'm using:
Python version 3.4.3 |Anaconda 2.2.0 (x86_64)| (default, Mar  6 2015, 12:07:41) 
[GCC 4.2.1 (Apple Inc. build 5577)]
Pandas version: 0.15.2

In [3]: url_template = "http://climate.weather.gc.ca/climateData/bulkdata_e.html?format=csv&stationID=5415&Year={year}&Month={month}&timeframe=1&submit=Download+Data"
    url = url_template.format(month=3, year=2012)
    weather_mar2012 = pd.read_csv(url, skiprows=16, index_col='Date/Time', parse_dates=True, encoding='latin1')
    weather_mar2012

The result is this: 

ValueError                                Traceback (most recent call last)
<ipython-input-3-a2302d772b77> in <module>()
----> 6 weather_mar2012 = pd.read_csv(url, skiprows=16, index_col='Date/Time', parse_dates=True, encoding='latin1')
...
--> 465         return _read(filepath_or_buffer, kwds)
...
--> 241     parser = TextFileReader(filepath_or_buffer, **kwds)
...
--> 557         self._make_engine(self.engine)
...
--> 694             self._engine = CParserWrapper(self.f, **self.options)
...
--> 1061         self._reader = _parser.TextReader(src, **kwds)
...
pandas/parser.pyx in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4804)()
ValueError: No columns to parse from file

**Comment by michaelreinhard** [comment]
I have had the same problem with tutorial 5 I think, though I am using python 2.7 something. I had no problem with the prior four tutorials and learned a lot, but I got stuck on the In[4] even though I am able to download the file on my own cutting and pasting the URL into my own browser.

**Comment by aabroder** [comment]
Oh cool, I just looked at the tutorials here (and not at the Pandas site). Code here works. Thank you!
