### ISSUE TITLE
Quick Tour is only compatible with Python 2.7

### ISSUE THREAD

**Issue by CaliLuke** [jvns/pandas-cookbook#38]
I think it's about time to start either calling out the version you're expecting users to have or update the examples to work with Python 3.x

The [very first example](http://nbviewer.ipython.org/github/jvns/pandas-cookbook/blob/master/cookbook/A%20quick%20tour%20of%20IPython%20Notebook.ipynb) doesn't work with Python 3.x

```python
print "Hi! This is a cell. Press the ▶ button above to run it"
```
should be 
```python
print("Hi! This is a cell. Press the ▶ button above to run it")
```

**Comment by jvns** [comment]
Updated the README to say that it's using Python 2.7.
