### ISSUE TITLE
Broken link on the home page

### ISSUE THREAD

**Issue by ramanraja** [jvns/pandas-cookbook#82]
In the home page
https://github.com/jvns/pandas-cookbook -> Table of Contents -> "A quick tour of the Jupyter Notebook" links to the following:
`http://nbviewer.jupyter.org/github/jvns/pandas-cookbook/blob/master/cookbook/A%20quick%20tour%20of%20%20Notebook.ipynb`
This link is broken.

**Comment by jvns** [comment]
Thanks, fixed in 3b1c3d613c16255662f34953f5db20e809614473
